### ISSUE TITLE
Excluded event still shows up?

### ISSUE THREAD

**Issue by fribse** [billgraziano/xelogstash#93]
Hi @billgraziano 
I added an excluded event

```
excludedEvents = [
    "connectivity_ring_buffer_recorded",
    "memory_broker_ring_buffer_recorded",
    "scheduler_monitor_system_health_ring_buffer_recorded",
    "security_error_ring_buffer_recorded",
	"sp_server_diagnostics_component_result",
	"sp_reset_connection"
    ]
```
But when I look at the input, it still shows up?
![billede](https://github.com/billgraziano/xelogstash/assets/13660621/14ad0d59-07e9-4d48-b578-90ed4bd79cf8)

**Comment by fribse** [comment]
I think I figured that one out after pasting it here.
Notepad++ changed the spaces on the added lines to TAB.
I've changed it to spaces instead, and it now seems to read it properly.
Doesn't seem to affect the 'adds' statement though?

**Comment by billgraziano** [comment]
`exec sp_reset_connection` is an `rpc_completed` event and not a SQL Server Extended Event.  There are a few ways to remove it:

1. Filter it out at the Extended Event itself.  See https://github.com/billgraziano/xelogstash/blob/master/samples/logstash_events.sql for some sample filters.

2. Create a filter in this app.  See https://github.com/billgraziano/xelogstash#app-settings.  That may look something like this:

```
[[filter]]
filter_action = "exclude"
name = "rpc_completed"
the_field_name = "exec sp_reset_connection"
```

I can't remember which field this is in.  You'll have to look at the JSON and replace `the_field_name` with the actual field.

3. I don't capture event SQL event -- only "interesting" ones.  So in "1" above I only include `rpc_completed` events that have a certain number of reads or CPU which eliminates these.

**Comment by fribse** [comment]
Hi Bill
I can see the logfile grows very fast, too fast for it to be viable in the current form, as you also pointed out.
I don't know much about mssql servers, so I'm a bit confused about how much the logstash_events.sql gives me.
I need to do some sort of audit on these mssql servers, as they have private and personal data in them for a lot of people.
Will the logstash_events file give me selects etc.?

**Comment by billgraziano** [comment]
This isn't designed for true auditing.  It is designed to capture extended events which are typically used for monitoring and troubleshooting -- and have a much lower volume.  Likely capturing ever SQL statement would be problematic.

If you have to capture SELECTs on certain tables, you probably want to use SQL Server Auditing.  But that is going to generate huge amounts of data.  You will need some way to capture that.

I can help with that, but it will be in my role as a consultant rather than a free software developer:  https://www.scalesql.com/contact/
